package com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.config;

import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.config.refinement.BaswareConnectorOauth2aprilv2ConfigurationRefinement;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.connection.provider.BearerConnectionProvider;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.connection.provider.Oauth2authenticationConnectionProvider;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1AccountingDocumentsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1AccountsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1AdvancedPermissionsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1AdvancedValidationsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1ContractsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1CostCentersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1ErrorFeedbacksOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1ExchangeRatesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1ExportedContractSpendsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1ExportedContractsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1ExportedPurchaseOrdersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1ExportedPurchaseRequisitionsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1ListsListKeyOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1MatchingOrderLinesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1MatchingOrdersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1PaymentTermsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1ProjectsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1PurchaseGoodsReceiptsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1PurchaseOrdersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1PurchaseRequisitionsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1TaxCodesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1UsersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV1VendorsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.DeleteV2ProjectsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1AccountingDocumentsInvoiceIdOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1AccountingDocumentsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1AccountsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1AccountsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1AdvancedPermissionsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1AdvancedPermissionsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1AdvancedValidationsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1AdvancedValidationsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ApplicationGroupsApplicationGroupCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ApplicationGroupsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1CompaniesCompanyCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1CompaniesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ContractsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ContractsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1CostCentersExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1CostCentersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ErrorFeedbacksEntityTypeErrorEntityExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ErrorFeedbacksOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ErrorFeedbacksRequestIdOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ExchangeRatesExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ExchangeRatesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ExportedContractSpendsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ExportedContractSpendsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ExportedContractsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ExportedContractsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ExportedPurchaseOrdersExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ExportedPurchaseOrdersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ExportedPurchaseRequisitionsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ExportedPurchaseRequisitionsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ListsListKeyExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ListsListKeyOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1MatchingOrderLinesExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1MatchingOrderLinesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1MatchingOrdersExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1MatchingOrdersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1PaymentTermsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1PaymentTermsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ProjectsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1ProjectsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1PurchaseGoodsReceiptsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1PurchaseGoodsReceiptsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1PurchaseOrdersExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1PurchaseOrdersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1PurchaseRequisitionsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1PurchaseRequisitionsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1RequestStatusOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1RequestStatusRequestIdOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1TaxCodesExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1TaxCodesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1UsersExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1UsersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1VendorsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV1VendorsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV2ProjectsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.GetV2ProjectsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1AccountsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1AdvancedPermissionsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1AdvancedValidationsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1ContractsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1CostCentersExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1ExchangeRatesExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1ListsListKeyExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1MatchingOrderLinesExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1MatchingOrdersExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1PaymentTermsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1ProjectsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1PurchaseOrdersExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1TaxCodesExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1UsersExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV1VendorsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PatchV2ProjectsExternalCodeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1AccountingDocumentsInvoiceIdAcknowledgeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1AccountingDocumentsInvoiceIdPaymentResponsesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1AccountingDocumentsInvoiceIdPrebookResponsesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1AccountingDocumentsInvoiceIdTransferResponsesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1AccountsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1AdvancedPermissionsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1AdvancedValidationsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1ApplicationGroupsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1CompaniesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1ContractsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1CostCentersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1ExchangeRatesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1ExportedContractSpendsAcknowledgeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1ExportedContractsAcknowledgeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1ExportedPurchaseOrdersExternalCodeAcknowledgeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1ExportedPurchaseRequisitionsExternalCodeAcknowledgeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1ListsListKeyOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1MatchingOrderLinesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1MatchingOrdersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1PaymentTermsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1ProjectsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1PurchaseGoodsReceiptsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1PurchaseOrdersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1PurchaseRequisitionsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1RedistributeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1RequestStatusAcknowledgeOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1TaxCodesOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1UsersOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV1VendorsOperation;
import com.mulesoft.connectors.baswareconnectoroauth2aprilv2.internal.operation.PostV2ProjectsOperation;
import org.mule.runtime.extension.api.annotation.Configuration;
import org.mule.runtime.extension.api.annotation.Operations;
import org.mule.runtime.extension.api.annotation.connectivity.ConnectionProviders;

@Configuration
@Operations({
  GetV1AccountingDocumentsOperation.class,
  DeleteV1AccountingDocumentsOperation.class,
  GetV1AccountingDocumentsInvoiceIdOperation.class,
  PostV1AccountingDocumentsInvoiceIdAcknowledgeOperation.class,
  PostV1AccountingDocumentsInvoiceIdTransferResponsesOperation.class,
  PostV1AccountingDocumentsInvoiceIdPrebookResponsesOperation.class,
  PostV1AccountingDocumentsInvoiceIdPaymentResponsesOperation.class,
  GetV1AccountsOperation.class,
  PostV1AccountsOperation.class,
  DeleteV1AccountsOperation.class,
  GetV1AccountsExternalCodeOperation.class,
  PatchV1AccountsExternalCodeOperation.class,
  GetV1AdvancedPermissionsOperation.class,
  PostV1AdvancedPermissionsOperation.class,
  DeleteV1AdvancedPermissionsOperation.class,
  GetV1AdvancedPermissionsExternalCodeOperation.class,
  PatchV1AdvancedPermissionsExternalCodeOperation.class,
  GetV1AdvancedValidationsOperation.class,
  PostV1AdvancedValidationsOperation.class,
  DeleteV1AdvancedValidationsOperation.class,
  GetV1AdvancedValidationsExternalCodeOperation.class,
  PatchV1AdvancedValidationsExternalCodeOperation.class,
  PostV1ApplicationGroupsOperation.class,
  GetV1ApplicationGroupsOperation.class,
  GetV1ApplicationGroupsApplicationGroupCodeOperation.class,
  GetV1CompaniesOperation.class,
  PostV1CompaniesOperation.class,
  GetV1CompaniesCompanyCodeOperation.class,
  GetV1ContractsOperation.class,
  PostV1ContractsOperation.class,
  DeleteV1ContractsOperation.class,
  GetV1ContractsExternalCodeOperation.class,
  PatchV1ContractsExternalCodeOperation.class,
  GetV1CostCentersOperation.class,
  PostV1CostCentersOperation.class,
  DeleteV1CostCentersOperation.class,
  GetV1CostCentersExternalCodeOperation.class,
  PatchV1CostCentersExternalCodeOperation.class,
  GetV1ErrorFeedbacksOperation.class,
  DeleteV1ErrorFeedbacksOperation.class,
  GetV1ErrorFeedbacksRequestIdOperation.class,
  GetV1ErrorFeedbacksEntityTypeErrorEntityExternalCodeOperation.class,
  GetV1ExchangeRatesOperation.class,
  PostV1ExchangeRatesOperation.class,
  DeleteV1ExchangeRatesOperation.class,
  GetV1ExchangeRatesExternalCodeOperation.class,
  PatchV1ExchangeRatesExternalCodeOperation.class,
  GetV1ExportedContractsOperation.class,
  DeleteV1ExportedContractsOperation.class,
  GetV1ExportedContractsExternalCodeOperation.class,
  PostV1ExportedContractsAcknowledgeOperation.class,
  GetV1ExportedContractSpendsOperation.class,
  DeleteV1ExportedContractSpendsOperation.class,
  GetV1ExportedContractSpendsExternalCodeOperation.class,
  PostV1ExportedContractSpendsAcknowledgeOperation.class,
  GetV1ExportedPurchaseOrdersOperation.class,
  DeleteV1ExportedPurchaseOrdersOperation.class,
  GetV1ExportedPurchaseOrdersExternalCodeOperation.class,
  PostV1ExportedPurchaseOrdersExternalCodeAcknowledgeOperation.class,
  GetV1ExportedPurchaseRequisitionsOperation.class,
  DeleteV1ExportedPurchaseRequisitionsOperation.class,
  GetV1ExportedPurchaseRequisitionsExternalCodeOperation.class,
  PostV1ExportedPurchaseRequisitionsExternalCodeAcknowledgeOperation.class,
  GetV1ListsListKeyOperation.class,
  PostV1ListsListKeyOperation.class,
  DeleteV1ListsListKeyOperation.class,
  GetV1ListsListKeyExternalCodeOperation.class,
  PatchV1ListsListKeyExternalCodeOperation.class,
  GetV1MatchingOrderLinesOperation.class,
  PostV1MatchingOrderLinesOperation.class,
  DeleteV1MatchingOrderLinesOperation.class,
  GetV1MatchingOrderLinesExternalCodeOperation.class,
  PatchV1MatchingOrderLinesExternalCodeOperation.class,
  GetV1MatchingOrdersOperation.class,
  PostV1MatchingOrdersOperation.class,
  DeleteV1MatchingOrdersOperation.class,
  GetV1MatchingOrdersExternalCodeOperation.class,
  PatchV1MatchingOrdersExternalCodeOperation.class,
  GetV1PaymentTermsOperation.class,
  PostV1PaymentTermsOperation.class,
  DeleteV1PaymentTermsOperation.class,
  GetV1PaymentTermsExternalCodeOperation.class,
  PatchV1PaymentTermsExternalCodeOperation.class,
  GetV1ProjectsOperation.class,
  PostV1ProjectsOperation.class,
  DeleteV1ProjectsOperation.class,
  GetV1ProjectsExternalCodeOperation.class,
  PatchV1ProjectsExternalCodeOperation.class,
  GetV2ProjectsOperation.class,
  PostV2ProjectsOperation.class,
  DeleteV2ProjectsOperation.class,
  GetV2ProjectsExternalCodeOperation.class,
  PatchV2ProjectsExternalCodeOperation.class,
  GetV1PurchaseGoodsReceiptsOperation.class,
  PostV1PurchaseGoodsReceiptsOperation.class,
  DeleteV1PurchaseGoodsReceiptsOperation.class,
  GetV1PurchaseGoodsReceiptsExternalCodeOperation.class,
  GetV1PurchaseOrdersOperation.class,
  PostV1PurchaseOrdersOperation.class,
  DeleteV1PurchaseOrdersOperation.class,
  GetV1PurchaseOrdersExternalCodeOperation.class,
  PatchV1PurchaseOrdersExternalCodeOperation.class,
  GetV1PurchaseRequisitionsOperation.class,
  PostV1PurchaseRequisitionsOperation.class,
  DeleteV1PurchaseRequisitionsOperation.class,
  GetV1PurchaseRequisitionsExternalCodeOperation.class,
  PostV1RedistributeOperation.class,
  GetV1RequestStatusRequestIdOperation.class,
  GetV1RequestStatusOperation.class,
  PostV1RequestStatusAcknowledgeOperation.class,
  GetV1TaxCodesOperation.class,
  PostV1TaxCodesOperation.class,
  DeleteV1TaxCodesOperation.class,
  GetV1TaxCodesExternalCodeOperation.class,
  PatchV1TaxCodesExternalCodeOperation.class,
  GetV1UsersOperation.class,
  PostV1UsersOperation.class,
  DeleteV1UsersOperation.class,
  GetV1UsersExternalCodeOperation.class,
  PatchV1UsersExternalCodeOperation.class,
  GetV1VendorsOperation.class,
  PostV1VendorsOperation.class,
  DeleteV1VendorsOperation.class,
  GetV1VendorsExternalCodeOperation.class,
  PatchV1VendorsExternalCodeOperation.class
})
@ConnectionProviders({BearerConnectionProvider.class, Oauth2authenticationConnectionProvider.class})
public class BaswareConnectorOauth2aprilv2Configuration
    extends BaswareConnectorOauth2aprilv2ConfigurationRefinement {}
