package com.mulesoft.connectors.baswareconnectormule4.api.metadata;

public enum PatchV1ListsListKeyExternalCodeOperationListKeyUriParamEnum {
  ACC_LIST_1("ACC_LIST_1"),

  ACC_LIST_2("ACC_LIST_2"),

  ACC_LIST_3("ACC_LIST_3"),

  ACC_LIST_4("ACC_LIST_4"),

  ACC_LIST_5("ACC_LIST_5"),

  ACC_LIST_6("ACC_LIST_6"),

  ACC_LIST_7("ACC_LIST_7"),

  ACC_LIST_8("ACC_LIST_8"),

  ACC_LIST_9("ACC_LIST_9"),

  ACC_LIST_10("ACC_LIST_10"),

  ACC_LIST_11("ACC_LIST_11"),

  ACC_LIST_12("ACC_LIST_12"),

  ACC_LIST_13("ACC_LIST_13"),

  ACC_LIST_14("ACC_LIST_14"),

  ACC_LIST_15("ACC_LIST_15"),

  ACC_LIST_16("ACC_LIST_16"),

  ACC_LIST_17("ACC_LIST_17"),

  ACC_LIST_18("ACC_LIST_18"),

  ACC_LIST_19("ACC_LIST_19"),

  ACC_LIST_20("ACC_LIST_20"),

  ACC_LIST_21("ACC_LIST_21"),

  ACC_LIST_22("ACC_LIST_22"),

  ACC_LIST_23("ACC_LIST_23"),

  ACC_LIST_24("ACC_LIST_24"),

  ACC_LIST_25("ACC_LIST_25"),

  ACC_LIST_26("ACC_LIST_26"),

  ACC_LIST_27("ACC_LIST_27"),

  ACC_LIST_28("ACC_LIST_28"),

  ACC_LIST_29("ACC_LIST_29"),

  ACC_LIST_30("ACC_LIST_30"),

  ACC_LIST_31("ACC_LIST_31"),

  ACC_LIST_32("ACC_LIST_32"),

  ACC_LIST_33("ACC_LIST_33"),

  ACC_LIST_34("ACC_LIST_34"),

  ACC_LIST_35("ACC_LIST_35"),

  CUST_RESOLVER_1("CUST_RESOLVER_1"),

  CUST_RESOLVER_2("CUST_RESOLVER_2"),

  CUST_RESOLVER_3("CUST_RESOLVER_3"),

  CUST_RESOLVER_4("CUST_RESOLVER_4"),

  CUST_RESOLVER_5("CUST_RESOLVER_5"),

  INV_LIST_1("INV_LIST_1"),

  INV_LIST_2("INV_LIST_2"),

  INV_LIST_3("INV_LIST_3"),

  INV_LIST_4("INV_LIST_4"),

  INV_LIST_5("INV_LIST_5"),

  INV_LIST_6("INV_LIST_6"),

  INV_LIST_7("INV_LIST_7"),

  INV_LIST_8("INV_LIST_8"),

  INV_LIST_9("INV_LIST_9"),

  INV_LIST_10("INV_LIST_10"),

  INV_LIST_11("INV_LIST_11"),

  INV_LIST_12("INV_LIST_12"),

  INV_LIST_13("INV_LIST_13"),

  INV_LIST_14("INV_LIST_14"),

  INV_LIST_15("INV_LIST_15"),

  INV_LIST_16("INV_LIST_16"),

  INV_LIST_17("INV_LIST_17"),

  INV_LIST_18("INV_LIST_18"),

  INV_LIST_19("INV_LIST_19"),

  INV_LIST_20("INV_LIST_20");

  private String value;

  PatchV1ListsListKeyExternalCodeOperationListKeyUriParamEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }
}
